version: '3.1'

services:
  nextjs:
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: blog.example.com
      LETSENCRYPT_HOST: blog.example.com
      LETSENCRYPT_EMAIL: foo@example.com
    container_name: marco-trevisani