services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marco-trevisani
    environment:
      LETSENCRYPT_EMAIL: info@marcotrevisani.com
      LETSENCRYPT_HOST: www.marcotrevisani.com
      VIRTUAL_HOST: www.marcotrevisani.com
      VIRTUAL_PORT: 3000
    ports:
      - "3000:3000"
    restart: always

networks:
  default:
    name: nginx-proxy
    external: true
